In [3]:
import pandas as pd
import polars as pl
import pyarrow.dataset as ds

In [4]:
ruta_parquet_tomtom = 'data/raw/tomtom_move_reports/segments_1_to_31_aug_2024.parquet'
df_tomtom_lazy = pl.scan_parquet(ruta_parquet_tomtom)

df_tomtom = df_tomtom_lazy.collect()
df_tomtom.head(20)

shape: (20, 23)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ date      ┆ station_i ┆ station_n ┆ segment_i ┆ … ┆ median_tr ┆ travel_ti ┆ speed_per ┆ geometry │
│ ---       ┆ d         ┆ ame       ┆ d         ┆   ┆ avel_time ┆ me_ratio  ┆ centiles  ┆ _wkt     │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ i64       ┆ str       ┆ i64       ┆   ┆ f64       ┆ f64       ┆ list[i64] ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2024-08-0 ┆ 0         ┆ CENTRO    ┆ -14840000 ┆ … ┆ 11.95     ┆ 1.0       ┆ [16, 16,  ┆ LINESTRI │
│ 1         ┆           ┆           ┆ 675661    ┆   ┆           ┆           ┆ … 29]     ┆ NG (-100 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .3201    │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 25.66233 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ …        │
│ 2024-08-0 ┆ 0         ┆ CENTRO    ┆ -14840000 ┆ … ┆ 11.53     ┆ 0.89      ┆ [19, 19,  ┆ LINESTRI │
│ 1         ┆           ┆           ┆ 675661    ┆   ┆           ┆           ┆ … 44]     ┆ NG (-100 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .3201    │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 25.66233 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ …        │
│ 2024-08-0 ┆ 0         ┆ CENTRO    ┆ -14840000 ┆ … ┆ 10.47     ┆ 0.91      ┆ [13, 13,  ┆ LINESTRI │
│ 1         ┆           ┆           ┆ 675661    ┆   ┆           ┆           ┆ … 47]     ┆ NG (-100 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .3201    │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 25.66233 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ …        │
│ 2024-08-0 ┆ 0         ┆ CENTRO    ┆ -14840000 ┆ … ┆ 31.41     ┆ 2.51      ┆ [9, 9, …  ┆ LINESTRI │
│ 1         ┆           ┆           ┆ 675661    ┆   ┆           ┆           ┆ 9]        ┆ NG (-100 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .3201    │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 25.66233 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ …        │
│ 2024-08-0 ┆ 0         ┆ CENTRO    ┆ -14840000 ┆ … ┆ 17.16     ┆ 1.3       ┆ [16, 16,  ┆ LINESTRI │
│ 1         ┆           ┆           ┆ 675661    ┆   ┆           ┆           ┆ … 23]     ┆ NG (-100 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .3201    │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 25.66233 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ …        │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2024-08-0 ┆ 0         ┆ CENTRO    ┆ -14840000 ┆ … ┆ 12.05     ┆ 1.16      ┆ [12, 14,  ┆ LINESTRI │
│ 1         ┆           ┆           ┆ 675661    ┆   ┆           ┆           ┆ … 37]     ┆ NG (-100 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .3201    │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 25.66233 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ …        │
│ 2024-08-0 ┆ 0         ┆ CENTRO    ┆ -14840000 ┆ … ┆ 13.48     ┆ 1.25      ┆ [10, 13,  ┆ LINESTRI │
│ 1         ┆           ┆           ┆ 675661    ┆   ┆           ┆           ┆ … 30]     ┆ NG (-100 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .3201    │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 25.66233 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ …        │
│ 2024-08-0 ┆ 0         ┆ CENTRO    ┆ -14840000 ┆ … ┆ 13.86     ┆ 1.36      ┆ [8, 11, … ┆ LINESTRI │
│ 1         ┆           ┆           ┆ 675661    ┆   ┆           ┆           ┆ 31]       ┆ NG (-100 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .3201    │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 25.66233 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ …        │
│ 2024-08-0 ┆ 0         ┆ CENTRO    ┆ -14840000 ┆ … ┆ 24.81     ┆ 2.13      ┆ [5, 7, …  ┆ LINESTRI │
│ 1         ┆           ┆           ┆ 675661    ┆   ┆           ┆           ┆ 28]       ┆ NG (-100 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .3201    │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 25.66233 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ …        │
│ 2024-08-0 ┆ 0         ┆ CENTRO    ┆ -14840000 ┆ … ┆ 18.57     ┆ 1.7       ┆ [7, 9, …  ┆ LINESTRI │
│ 1         ┆           ┆           ┆ 675661    ┆   ┆           ┆           ┆ 29]       ┆ NG (-100 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .3201    │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 25.66233 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ …        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

Usar filtros en caso de que no cuentes con la suficiente memoria fisica

In [5]:
df_tomtom.estimated_size('gb')

11.231291579082608

In [6]:
ruta_csv_sima = "data/processed/df_imputados_saits_agosto2024_schema.csv"
df_sima = pl.read_csv(ruta_csv_sima)
# filtrar a solo agosto
df_sima = df_sima.filter(
    pl.col("date").str.to_datetime(format="%Y-%m-%d %H:%M:%S").dt.month() == 8
)

In [7]:
df_sima

shape: (11_160, 13)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬─────────┬──────┐
│ date       ┆ CO        ┆ O3        ┆ NO        ┆ … ┆ WSR       ┆ WDR       ┆ Zona    ┆ Hora │
│ ---        ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---     ┆ ---  │
│ str        ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ str     ┆ i64  │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═════════╪══════╡
│ 2020-08-01 ┆ 0.4320273 ┆ 0.12782   ┆ -0.574229 ┆ … ┆ -0.740215 ┆ -0.28568  ┆ CENTRO  ┆ 0    │
│ 00:00:00   ┆           ┆           ┆           ┆   ┆           ┆           ┆         ┆      │
│ 2020-08-01 ┆ 0.146703  ┆ -0.804815 ┆ -0.342889 ┆ … ┆ -0.524414 ┆ -0.441396 ┆ NORTE   ┆ 0    │
│ 00:00:00   ┆           ┆           ┆           ┆   ┆           ┆           ┆         ┆      │
│ 2020-08-01 ┆ 0.175362  ┆ -0.654244 ┆ -0.174292 ┆ … ┆ 0.474146  ┆ 1.9782051 ┆ SURESTE ┆ 0    │
│ 00:00:00   ┆           ┆           ┆           ┆   ┆           ┆           ┆         ┆      │
│ 2020-08-01 ┆ 0.349854  ┆ -0.353787 ┆ -0.542342 ┆ … ┆ -0.605792 ┆ -0.612095 ┆ CENTRO  ┆ 1    │
│ 01:00:00   ┆           ┆           ┆           ┆   ┆           ┆           ┆         ┆      │
│ 2020-08-01 ┆ -0.029441 ┆ -0.902438 ┆ -0.458232 ┆ … ┆ -0.491588 ┆ -0.424872 ┆ NORTE   ┆ 1    │
│ 01:00:00   ┆           ┆           ┆           ┆   ┆           ┆           ┆         ┆      │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …       ┆ …    │
│ 2024-08-31 ┆ 0.8427421 ┆ -0.56607  ┆ -0.38752  ┆ … ┆ -0.687515 ┆ -0.168488 ┆ NORTE   ┆ 22   │
│ 22:00:00   ┆           ┆           ┆           ┆   ┆           ┆           ┆         ┆      │
│ 2024-08-31 ┆ -0.004613 ┆ -1.270482 ┆ 0.4326014 ┆ … ┆ -1.10745  ┆ 0.175888  ┆ SURESTE ┆ 22   │
│ 22:00:00   ┆           ┆           ┆           ┆   ┆           ┆           ┆         ┆      │
│ 2024-08-31 ┆ -0.731364 ┆ -0.841849 ┆ -0.468965 ┆ … ┆ -0.916907 ┆ -0.27868  ┆ CENTRO  ┆ 23   │
│ 23:00:00   ┆           ┆           ┆           ┆   ┆           ┆           ┆         ┆      │
│ 2024-08-31 ┆ 1.0707972 ┆ -0.973144 ┆ -0.263073 ┆ … ┆ -0.468723 ┆ -0.118816 ┆ NORTE   ┆ 23   │
│ 23:00:00   ┆           ┆           ┆           ┆   ┆           ┆           ┆         ┆      │
│ 2024-08-31 ┆ 0.23086   ┆ -1.324475 ┆ 0.814616  ┆ … ┆ -0.357237 ┆ -0.742674 ┆ SURESTE ┆ 23   │
│ 23:00:00   ┆           ┆           ┆           ┆   ┆           ┆           ┆         ┆      │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴─────────┴──────┘

## Calculo de candidatos

In [8]:
df_tomtom = df_tomtom[['date', 'hour_start', 'station_name', 'segment_id', 'street_name', 'sample_size', 'travel_time_ratio', 'frc', 'avg_speed', 'distance_m']] # agrega columnas si lo requieres para calcular otra variable


# numero de muestras en la zona de la estacion
df_tomtom_suma_muestra = df_tomtom.group_by([
        'date',
        'hour_start',
        'station_name'
    ]).agg(
        pl.col('sample_size').sum().alias('total_sample_size_per_hour')
    ).sort(['station_name', 'date', 'hour_start'])

# avg_tti_street (de Ana Valverde)
df_tomtom_avg_tti_street = df_tomtom.filter(
    (pl.col("frc") <= 4)
    & (pl.col("sample_size") >= 10)
).group_by([
        'date',
        'hour_start',
        'station_name'
    ]).agg(
        pl.col("travel_time_ratio").mean().alias("avg_tti_street")
    ).sort(['station_name', 'date', 'hour_start'])


# Índice de Congestión Vehicular (de Rene)
import polars as pl

FRC_to_lanes = {
    0: 3,
    1: 2,
    2: 2,
    3: 2,
    4: 1,
    5: 1,
    6: 1,
    7: 1,
}

JAM_DENSITY_PER_LANE = 150  # por ejemplo

df_tomtom_vci_per_segment = (
    df_tomtom
    .with_columns(
        pl.col("frc").replace(FRC_to_lanes).alias("lanes")
    )
    .with_columns(
        pl.col("avg_speed").max().over("date").alias("free_flow_speed")
    )
    .with_columns(
        (JAM_DENSITY_PER_LANE * (1 - pl.col("avg_speed") / pl.col("free_flow_speed")))
        .alias("est_density_per_lane")
    )
    .with_columns(
        (pl.col("est_density_per_lane") * pl.col("lanes")).alias("est_density_total")
    )
    .with_columns(
        (pl.col("distance_m") / 1000).alias("distance_km")
    )
    .with_columns(
        (pl.col("est_density_total") * pl.col("distance_km"))
        .alias("estimated_vehicles_in_segment")
    )
    .with_columns(
        (pl.col("est_density_total") / (JAM_DENSITY_PER_LANE * pl.col("lanes")))
        .alias("congestion_ratio")
    )
)

df_tomtom_vci_mean = (df_tomtom_vci_per_segment
                      .group_by([
                        'date',
                        'hour_start',
                        'station_name'
                    ]).agg(
                        pl.col("congestion_ratio").mean().alias("congestion_ratio_mean"))
                        .sort(['station_name', 'date', 'hour_start']))

df_tomtom_vci_mean

shape: (2_232, 4)
┌────────────┬────────────┬──────────────┬───────────────────────┐
│ date       ┆ hour_start ┆ station_name ┆ congestion_ratio_mean │
│ ---        ┆ ---        ┆ ---          ┆ ---                   │
│ str        ┆ i64        ┆ str          ┆ f64                   │
╞════════════╪════════════╪══════════════╪═══════════════════════╡
│ 2024-08-01 ┆ 0          ┆ CENTRO       ┆ 0.888761              │
│ 2024-08-01 ┆ 1          ┆ CENTRO       ┆ 0.899864              │
│ 2024-08-01 ┆ 2          ┆ CENTRO       ┆ 0.907337              │
│ 2024-08-01 ┆ 3          ┆ CENTRO       ┆ 0.914764              │
│ 2024-08-01 ┆ 4          ┆ CENTRO       ┆ 0.915134              │
│ …          ┆ …          ┆ …            ┆ …                     │
│ 2024-08-31 ┆ 19         ┆ SURESTE      ┆ 0.924295              │
│ 2024-08-31 ┆ 20         ┆ SURESTE      ┆ 0.925257              │
│ 2024-08-31 ┆ 21         ┆ SURESTE      ┆ 0.926729              │
│ 2024-08-31 ┆ 22         ┆ SURESTE      ┆ 0.925627              │
│ 2024-08-31 ┆ 23         ┆ SURESTE      ┆ 0.930113              │
└────────────┴────────────┴──────────────┴───────────────────────┘

## .

In [9]:
df_sima = df_sima.with_columns(
    pl.col("date").str.to_datetime(format="%Y-%m-%d %H:%M:%S").alias("date")
)
df_sima  = df_sima.with_columns(
    pl.col("date").dt.date().cast(pl.Utf8).alias("date_only")
)
df_sima = df_sima[['date_only', 'Hora', 'Zona', 'CO', 'NOX', 'O3', 'PM2.5', 'PM10']]
df_sima

shape: (11_160, 8)
┌────────────┬──────┬─────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ date_only  ┆ Hora ┆ Zona    ┆ CO        ┆ NOX       ┆ O3        ┆ PM2.5     ┆ PM10      │
│ ---        ┆ ---  ┆ ---     ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ i64  ┆ str     ┆ f64       ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪══════╪═════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2020-08-01 ┆ 0    ┆ CENTRO  ┆ 0.4320273 ┆ -0.913021 ┆ 0.12782   ┆ -0.295078 ┆ -0.924299 │
│ 2020-08-01 ┆ 0    ┆ NORTE   ┆ 0.146703  ┆ -0.273608 ┆ -0.804815 ┆ -0.144864 ┆ -0.151987 │
│ 2020-08-01 ┆ 0    ┆ SURESTE ┆ 0.175362  ┆ -0.085221 ┆ -0.654244 ┆ -0.085186 ┆ -0.386582 │
│ 2020-08-01 ┆ 1    ┆ CENTRO  ┆ 0.349854  ┆ -0.879366 ┆ -0.353787 ┆ -0.283051 ┆ -0.373601 │
│ 2020-08-01 ┆ 1    ┆ NORTE   ┆ -0.029441 ┆ -0.448003 ┆ -0.902438 ┆ -0.263416 ┆ -0.199275 │
│ …          ┆ …    ┆ …       ┆ …         ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2024-08-31 ┆ 22   ┆ NORTE   ┆ 0.8427421 ┆ -0.054657 ┆ -0.56607  ┆ -0.016848 ┆ -0.775322 │
│ 2024-08-31 ┆ 22   ┆ SURESTE ┆ -0.004613 ┆ 1.0353338 ┆ -1.270482 ┆ -1.005733 ┆ -0.272331 │
│ 2024-08-31 ┆ 23   ┆ CENTRO  ┆ -0.731364 ┆ -0.088179 ┆ -0.841849 ┆ -0.696515 ┆ -0.686773 │
│ 2024-08-31 ┆ 23   ┆ NORTE   ┆ 1.0707972 ┆ 0.2558053 ┆ -0.973144 ┆ 0.074413  ┆ -0.677965 │
│ 2024-08-31 ┆ 23   ┆ SURESTE ┆ 0.23086   ┆ 1.27314   ┆ -1.324475 ┆ -0.991884 ┆ 0.196269  │
└────────────┴──────┴─────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

In [10]:
df_sima_union_candidato = df_sima.join(
    df_tomtom_suma_muestra,
    left_on=['date_only', 'Hora', 'Zona'],
    right_on=['date', 'hour_start', 'station_name'],
    how='left'
)

df_sima_union_candidato = df_sima_union_candidato.join(
    df_tomtom_avg_tti_street,
    left_on=['date_only', 'Hora', 'Zona'],
    right_on=['date', 'hour_start', 'station_name'],
    how='left'
)

df_sima_union_candidato = df_sima_union_candidato.join(
    df_tomtom_vci_mean,
    left_on=['date_only', 'Hora', 'Zona'],
    right_on=['date', 'hour_start', 'station_name'],
    how='left'
)

df_sima_union_candidato

shape: (11_160, 11)
┌────────────┬──────┬─────────┬───────────┬───┬───────────┬─────────────┬─────────────┬────────────┐
│ date_only  ┆ Hora ┆ Zona    ┆ CO        ┆ … ┆ PM10      ┆ total_sampl ┆ avg_tti_str ┆ congestion │
│ ---        ┆ ---  ┆ ---     ┆ ---       ┆   ┆ ---       ┆ e_size_per_ ┆ eet         ┆ _ratio_mea │
│ str        ┆ i64  ┆ str     ┆ f64       ┆   ┆ f64       ┆ hour        ┆ ---         ┆ n          │
│            ┆      ┆         ┆           ┆   ┆           ┆ ---         ┆ f64         ┆ ---        │
│            ┆      ┆         ┆           ┆   ┆           ┆ i64         ┆             ┆ f64        │
╞════════════╪══════╪═════════╪═══════════╪═══╪═══════════╪═════════════╪═════════════╪════════════╡
│ 2020-08-01 ┆ 0    ┆ CENTRO  ┆ 0.4320273 ┆ … ┆ -0.924299 ┆ null        ┆ null        ┆ null       │
│ 2020-08-01 ┆ 0    ┆ NORTE   ┆ 0.146703  ┆ … ┆ -0.151987 ┆ null        ┆ null        ┆ null       │
│ 2020-08-01 ┆ 0    ┆ SURESTE ┆ 0.175362  ┆ … ┆ -0.386582 ┆ null        ┆ null        ┆ null       │
│ 2020-08-01 ┆ 1    ┆ CENTRO  ┆ 0.349854  ┆ … ┆ -0.373601 ┆ null        ┆ null        ┆ null       │
│ 2020-08-01 ┆ 1    ┆ NORTE   ┆ -0.029441 ┆ … ┆ -0.199275 ┆ null        ┆ null        ┆ null       │
│ …          ┆ …    ┆ …       ┆ …         ┆ … ┆ …         ┆ …           ┆ …           ┆ …          │
│ 2024-08-31 ┆ 22   ┆ NORTE   ┆ 0.8427421 ┆ … ┆ -0.775322 ┆ 110445      ┆ 1.187061    ┆ 0.940748   │
│ 2024-08-31 ┆ 22   ┆ SURESTE ┆ -0.004613 ┆ … ┆ -0.272331 ┆ 257814      ┆ 1.289344    ┆ 0.925627   │
│ 2024-08-31 ┆ 23   ┆ CENTRO  ┆ -0.731364 ┆ … ┆ -0.686773 ┆ 505461      ┆ 1.070079    ┆ 0.883681   │
│ 2024-08-31 ┆ 23   ┆ NORTE   ┆ 1.0707972 ┆ … ┆ -0.677965 ┆ 88916       ┆ 1.141661    ┆ 0.945246   │
│ 2024-08-31 ┆ 23   ┆ SURESTE ┆ 0.23086   ┆ … ┆ 0.196269  ┆ 178795      ┆ 1.07573     ┆ 0.930113   │
└────────────┴──────┴─────────┴───────────┴───┴───────────┴─────────────┴─────────────┴────────────┘

In [11]:
# Remover fines de semana

df_sima_union_candidato = df_sima_union_candidato.filter(
    (pl.col('date_only').str.to_datetime(format="%Y-%m-%d").dt.weekday() != 6) &
    (pl.col('date_only').str.to_datetime(format="%Y-%m-%d").dt.weekday() != 7)
)

In [12]:
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
def plot_candidate_v_contaminant(df ,candidate, contaminant):

    plt.figure(figsize=(10, 6))

    sns.regplot(
        x=candidate,
        y=contaminant,
        data=df.to_pandas(),
        scatter_kws={'alpha': 0.5},
        line_kws={'color': 'red', 'lw': 2}
    )

    mean_contaminant = df[contaminant].mean()

    plt.axhline(
        y=mean_contaminant,
        color='blue',
        linestyle='--',
        linewidth=2,
        label=f'Media de {contaminant}: {mean_contaminant:.2f}'
    )

    plt.title(f'Scatterplot de {candidate} vs {contaminant} en {df["Zona"][0]}')
    plt.xlabel(candidate)
    plt.ylabel(contaminant)
    plt.legend()
    plt.grid(True)

    plt.show()

In [14]:
def plot_centros_candidate_v_contamintant(df, candidate, contaminant):
    df_sima_union_candidato_norte = df.filter(pl.col('Zona') == "NORTE")
    df_sima_union_candidato_sureste = df.filter(pl.col('Zona') == "SURESTE")
    df_sima_union_candidato_centro = df.filter(pl.col('Zona') == "CENTRO")
    plot_candidate_v_contaminant(df_sima_union_candidato_norte, candidate, contaminant)
    plot_candidate_v_contaminant(df_sima_union_candidato_sureste, candidate, contaminant)
    plot_candidate_v_contaminant(df_sima_union_candidato_centro, candidate, contaminant)

In [ ]:
plot_centros_candidate_v_contamintant(df_sima_union_candidato, 'total_sample_size_per_hour', 'O3')
plot_centros_candidate_v_contamintant(df_sima_union_candidato, 'avg_tti_street', 'O3')
plot_centros_candidate_v_contamintant(df_sima_union_candidato, 'congestion_ratio_mean', 'O3')